name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'  # 只在以 v 开头的标签推送时触发，例如 v1.0.0

jobs:

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 清理 Docker
        run: docker system prune -af --volumes

      - name: 清理 APT 缓存
        run: sudo apt-get clean && sudo apt-get autoremove -y

      - name: 清理 npm 缓存
        run: npm cache clean --force

      - name: 清理 Python 缓存
        run: pip cache purge

      - name: 删除不必要的文件
        run: rm -rf ~/.cache

  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
